options:
  merge-default-rules: true
  formatter: stylish
files:
  include: 'app/**/*.s+(a|c)ss'
rules:
  border-zero:
    - 2
    -
      convention: '0'
  brace-style:
    - 2
    -
      style: 1tbs
      allow-single-line: false
  clean-import-paths:
    - 0
  empty-line-between-blocks: 2
  extends-before-declarations: 0
  extends-before-mixins: 0
  hex-length:
    - 2
    -
      style: short
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  leading-zero: 0
  mixins-before-declarations: 0
  nesting-depth: 0
  no-color-literals: 0
  no-empty-rulesets: 2
  no-extends: 2
  no-ids: 2
  no-important: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    -
      extra-properties:
        - composes
  no-qualifying-elements: 0
  no-url-protocols: 0
  property-sort-order: 0
  quotes:
    - 2
    -
      style: single
  single-line-per-selector: 2
  variable-for-property:
    - 2
    -
      properties:
        - color
