/*
 * LOGIN
 */
export const LOGIN_INITIATED = 'LOGIN_INITIATED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

/*
 * MOVIE
 */
export const LOADING_MOVIES = 'LOADING_MOVIES';
export const MOVIES_QUEUE_LOADED = 'MOVIES_QUEUE_LOADED';
export const SAVED_MOVIES_LOADED = 'SAVED_MOVIES_LOADED';
export const DISMISSED_MOVIES_LOADED = 'DISMISSED_MOVIES_LOADED';
export const MOVIES_ALREADY_LOADED = 'MOVIES_ALREADY_LOADED';
export const FAILED_LOADING_MOVIES = 'FAILED_LOADING_MOVIES';
export const SAVING_MOVIE = 'SAVING_MOVIE';
export const SAVED_MOVIE = 'SAVED_MOVIE';
export const DISMISSING_MOVIE = 'DISMISSING_MOVIE';
export const DISMISSED_MOVIE = 'DISMISSED_MOVIE';
export const UNDISMISSING_MOVIE = 'UNDISMISSING_MOVIE';
export const UNDISMISSED_MOVIE = 'UNDISMISSED_MOVIE';
export const FAILED_UPDATING_MOVIE = 'FAILED_UPDATING_MOVIE';
