/*
 * LOGIN
 */
export const LOGIN_INITIATED = 'LOGIN_INITIATED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

/*
 * MOVIE
 */
export const LOADING_MOVIES = 'LOADING_MOVIES';
export const MOVIES_LOADED = 'MOVIES_LOADED';
export const MOVIES_ALREADY_LOADED = 'MOVIES_ALREADY_LOADED';
export const FAILED_LOADING_MOVIES = 'FAILED_LOADING_MOVIES';
export const UPDATING_MOVIE = 'UPDATING_MOVIE';
export const FAILED_UPDATING_MOVIE = 'FAILED_UPDATING_MOVIE';
export const SAVED_MOVIE = 'SAVED_MOVIE';
export const DISMISSED_MOVIE = 'DISMISSED_MOVIE';
export const UNDISMISSED_MOVIE = 'UNDISMISSED_MOVIE';
export const ADD_MOVIE = 'ADD_MOVIE';
export const REMOVE_MOVIE = 'REMOVE_MOVIE';
